FROM jenkins/jenkins

USER root

RUN echo "teste"
RUN apt-get update && apt-get -y install lsb-release 
RUN apt -y install lsb-release apt-transport-https ca-certificates

# RUN chmod -R 777 /var/run/docker.sock
# RUN apt-get update && \
#     apt-get install -y software-properties-common && \
#     rm -rf /var/lib/apt/lists/*

# RUN add-apt-repository ppa:openjdk-r/ppa 
# RUN apt-get update && apt-get -y install openjdk-11-jdk

# RUN export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64


