version: '3'

services:
  jenkins:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: jenkinsci/blueocean
    ports:
      - '8082:8080'
      - '50000:50000'
    volumes:
      - 'c:\dev\docker:/var/jenkins_home'
      - '//var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - adoptopenjdk/openjdk11:latest
volumes:
  volume_jenkins:
    driver: local
