
pipeline {
    agent any
    tools {
        maven "3.6.0"
    }
    stages {
        stage('Build') {
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
        stage('Test') {
            steps {
                sh "mvn clean install"
            }
        }
    }
}