version: '3.3'
services:
  db:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: db
    environment:
     - POSTGRES_PASSWORD=123
    ports:
     - "5432:5432"
    volumes:
    - ./db/pg_volume/:/var/lib/postgresql/data

  rd:
    image: redis
#    container_name: redis1
    ports:
      - "6379:6379"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL